name: Scheduled Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # At 00:00

jobs:
  run:
    name: "Run price_scraper"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install price_scraper
        run: pip install git+https://github.com/andhrelja/price_scraper
